# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Reva Application using Node.JS and Gatsby

on:
  push:
    branches: [ "main" ]

jobs:
  build-the-app:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: "18.2.0"
        cache: 'npm'

    - name: Install Gatsby Framework
      run: npm install -g gatsby-cli

    - name: Install Libraries
      run: npm install

    - name: Unit Testing
      run: echo  "Unit Testing is going on"

  software-component-analysis:

    runs-on: ubuntu-latest
    needs: build-the-app
    steps:

    - uses: actions/checkout@v3

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: "18.2.0"
        cache: 'npm'

    - name: Install Gatsby Framework
      run: npm install -g gatsby-cli

    - name: Install Libraries
      run: npm install

    - name: Running NPM Audit
      run: npm audit --json >> npm-audit-report.json
      continue-on-error: true

    - name: Upload the Artifact
      uses: actions/upload-artifact@v3
      with:
        name: npm-audit-report
        path: npm-audit-report.json

  functional-testing:

    runs-on: ubuntu-latest
    needs: software-component-analysis
    steps: 

      - run: echo "Running Functional Testing"

  regression-testing:

    runs-on: ubuntu-latest
    needs: software-component-analysis
    steps: 

      - run: echo "Running regression Testing"

  deployment:

    runs-on: ubuntu-latest
    needs: [functional-testing, regression-testing ]
    steps: 

      - run: echo "Do the Deployment"

    
    