# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: My Reva Application using Node.JS and Gatsby

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Install Node.JS
      uses: actions/setup-node@v3
      with:
        node-version: "18.2.0"
        cache: 'npm'

    - name: Install Gatsby Framework
      run: npm install -g gatsby-cli

    - name: Install Libraries
      run: npm install

    - name: Unit Testing
      run: echo  "Unit Testing is going on"

    